version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /infra/envs/dev
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /infra/envs/staging
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /infra/envs/prod
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /infra/modules/network
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /infra/modules/eks
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /infra/modules/storage
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /infra/modules/iam-workload
    schedule:
      interval: weekly

  - package-ecosystem: terraform
    directory: /infra/modules/edge
    schedule:
      interval: weekly
