apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/instance: portal-dev
    includeSelectors: false

replicas:
  - name: portal
    count: 2

images:
  - name: 123456789012.dkr.ecr.us-east-1.amazonaws.com/portal
    newTag: dev-0a1b2c3
